- name: "Install NodeJs"
  become: true
  shell: |
    curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
    bash n lts
    npm install -g n
    n 13.9.0
    node --version


- name: "Install PM2 globally"
  npm:
    name: pm2
    global: yes